### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sanjay-kv** [bishalde/Bloggoo#2]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by Vanshika-73** [comment]
Please assign me this taks. I would like to create this code of conduct file for this repository.

**Comment by bishalde** [comment]
Hey@Vanshika-73, Sure, you can proceed with it.!

Ctrate a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.

**Comment by Vanshika-73** [comment]
@bishalde sure, then please officially assign this issue to me.

**Comment by bishalde** [comment]
> @bishalde sure, then please officially assign this issue to me.

Sure!
